server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  freemarker:
    allow-request-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates/
  datasource:
    url: jdbc:mysql://localhost:3306/roletest
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
